# Naive Baye's Machine Learning Algorithm

In [107]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

X,y = load_iris(return_X_y= True)

In [108]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.2],
       [5. , 3.2, 1.2, 0.2],
       [5.5, 3.5, 1.3, 0.2],
       [4.9, 3.6, 1.4, 0.1],
       [4.4, 3. , 1.3, 0.2],
       [5.1, 3.4, 1.5, 0.2],
       [5. , 3.5, 1.3, 0.3],
       [4.5, 2.3, 1.3, 0.3],
       [4.4, 3.2, 1.3, 0.2],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.9, 0.4],
       [4.8, 3. , 1.4, 0.3],
       [5.1, 3.8, 1.6, 0.2],
       [4.6, 3.2, 1.4, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5. , 3.3, 1.4, 0.2],
       [7. , 3.2, 4.7, 1.4],
       [6.4, 3.2, 4.5, 1.5],
       [6.9, 3.1, 4.9, 1.5],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 2.8, 4.6, 1.5],
       [5.7, 2.8, 4.5, 1.3],
       [6.3, 3.3, 4.7, 1.6],
       [4.9, 2.4, 3.3, 1. ],
       [6.6, 2.9, 4.6, 1.3],
       [5.2, 2.7, 3.9, 1.4],
       [5. , 2. , 3.5, 1. ],
       [5.9, 3. , 4.2, 1.5],
       [6. , 2.2, 4. , 1. ],
       [6.1, 2.9, 4.7, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [6.7, 3.1, 4.4, 1.4],
       [5.6, 3. , 4.5, 1.5],
       [5.8, 2.7, 4.1, 1. ],
       [6.2, 2.2, 4.5, 1.5],
       [5.6, 2.5, 3.9, 1.1],
       [5.9, 3.2, 4.8, 1.8],
       [6.1, 2.8, 4. , 1.3],
       [6.3, 2.5, 4.9, 1.5],
       [6.1, 2.8, 4.7, 1.2],
       [6.4, 2.9, 4.3, 1.3],
       [6.6, 3. , 4.4, 1.4],
       [6.8, 2.8, 4.8, 1.4],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.9, 4.5, 1.5],
       [5.7, 2.6, 3.5, 1. ],
       [5.5, 2.4, 3.8, 1.1],
       [5.5, 2.4, 3.7, 1. ],
       [5.8, 2.7, 3.9, 1.2],
       [6. , 2.7, 5.1, 1.6],
       [5.4, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [6.7, 3.1, 4.7, 1.5],
       [6.3, 2.3, 4.4, 1.3],
       [5.6, 3. , 4.1, 1.3],
       [5.5, 2.5, 4. , 1.3],
       [5.5, 2.6, 4.4, 1.2],
       [6.1, 3. , 4.6, 1.4],
       [5.8, 2.6, 4. , 1.2],
       [5. , 2.3, 3.3, 1. ],
       [5.6, 2.7, 4.2, 1.3],
       [5.7, 3. , 4.2, 1.2],
       [5.7, 2.9, 4.2, 1.3],
       [6.2, 2.9, 4.3, 1.3],
       [5.1, 2.5, 3. , 1.1],
       [5.7, 2.8, 4.1, 1.3],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [5.7, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6. , 2.2, 5. , 1.5],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [6.7, 3.3, 5.7, 2.1],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, 5.6, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [6.3, 3.4, 5.6, 2.4],
       [6.4, 3.1, 5.5, 1.8],
       [6. , 3. , 4.8, 1.8],
       [6.9, 3.1, 5.4, 2.1],
       [6.7, 3.1, 5.6, 2.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.8, 2.7, 5.1, 1.9],
       [6.8, 3.2, 5.9, 2.3],
       [6.7, 3.3, 5.7, 2.5],
       [6.7, 3. , 5.2, 2.3],
       [6.3, 2.5, 5. , 1.9],
       [6.5, 3. , 5.2, 2. ],
       [6.2, 3.4, 5.4, 2.3],
       [5.9, 3. , 5.1, 1.8]])

In [109]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [110]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [111]:
from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()

gnb.fit(X_train, y_train)

GaussianNB()

In [112]:
y_pred = gnb.predict(X_test)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print(accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        18
           2       1.00      1.00      1.00        11

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

[[16  0  0]
 [ 0 18  0]
 [ 0  0 11]]

In [113]:
import seaborn as sns

df = sns.load_dataset('tips')

In [114]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [116]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [117]:
X = df[['total_bill', 'tip','smoker', 'day', 'time', 'size']]
y = df[['sex']]

In [118]:
X

     total_bill   tip smoker   day    time  size
0         16.99  1.01     No   Sun  Dinner     2
1         10.34  1.66     No   Sun  Dinner     3
2         21.01  3.50     No   Sun  Dinner     3
3         23.68  3.31     No   Sun  Dinner     2
4         24.59  3.61     No   Sun  Dinner     4
..          ...   ...    ...   ...     ...   ...
239       29.03  5.92     No   Sat  Dinner     3
240       27.18  2.00    Yes   Sat  Dinner     2
241       22.67  2.00    Yes   Sat  Dinner     2
242       17.82  1.75     No   Sat  Dinner     2
243       18.78  3.00     No  Thur  Dinner     2

[244 rows x 6 columns]

In [119]:
y

        sex
0    Female
1      Male
2      Male
3      Male
4    Female
..      ...
239    Male
240  Female
241    Male
242    Male
243  Female

[244 rows x 1 columns]

In [120]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state = 42)

In [121]:
from sklearn.preprocessing import LabelEncoder

le1 = LabelEncoder()
le2 = LabelEncoder()

X_train['smoker'] = le1.fit_transform(X_train['smoker'])
X_train['time'] = le1.fit_transform(X_train['time'])

In [122]:
X_train

     total_bill   tip  smoker  day  time  size
115       17.31  3.50       0  Sun     0     2
181       23.33  5.65       1  Sun     0     2
225       16.27  2.50       1  Fri     1     2
68        20.23  2.01       0  Sat     0     2
104       20.92  4.08       0  Sat     0     2
..          ...   ...     ...  ...   ...   ...
106       20.49  4.06       1  Sat     0     2
14        14.83  3.02       0  Sun     0     2
92         5.75  1.00       1  Fri     0     2
179       34.63  3.55       1  Sun     0     2
102       44.30  2.50       1  Sat     0     3

[183 rows x 6 columns]

In [123]:
# One Hot Encoding - Column Transformer

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers= [('onehot', OneHotEncoder(drop='first'), [3],) ], remainder = 'passthrough')

import sys
import numpy as np

np.set_printoptions(threshold=sys.maxsize)

X_train = ct.fit_transform(X_train)

In [124]:
X_train

array([[ 0.  ,  1.  ,  0.  , 17.31,  3.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.33,  5.65,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 16.27,  2.5 ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.23,  2.01,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.92,  4.08,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.01,  2.09,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  7.25,  1.  ,  0.  ,  0.  ,  1.  ],
       [ 1.  ,  0.  ,  0.  , 26.59,  3.41,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 24.52,  3.48,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 19.77,  2.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 28.15,  3.  ,  1.  ,  0.  ,  5.  ],
       [ 0.  ,  0.  ,  1.  , 17.29,  2.71,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 19.65,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.53,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.45,  3.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 34.65,  3.68,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 25.29,  4.71,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 38.01,  3.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 29.8 ,  4.2 ,  0.  ,  1.  ,  6.  ],
       [ 0.  ,  0.  ,  1.  ,  9.78,  1.73,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 25.71,  4.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.08,  3.15,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 11.17,  1.5 ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 38.73,  3.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 16.21,  2.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 18.35,  2.5 ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 15.42,  1.57,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 24.06,  3.6 ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 21.7 ,  4.3 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 13.94,  3.06,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 29.03,  5.92,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  8.52,  1.48,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 16.32,  4.3 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.51,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.29,  2.6 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 40.17,  4.73,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 17.47,  3.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.58,  4.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.92,  3.08,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 17.46,  2.54,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 18.24,  3.76,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 15.98,  3.  ,  0.  ,  1.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 22.76,  3.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.43,  2.3 ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.37,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.07,  1.25,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 13.27,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.17,  6.5 ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 15.48,  2.02,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.99,  1.01,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 21.01,  3.5 ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 27.2 ,  4.  ,  0.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 22.23,  5.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 11.35,  2.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 14.15,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 11.87,  1.63,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 32.9 ,  3.11,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 28.97,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 34.83,  5.17,  0.  ,  1.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 50.81, 10.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 12.66,  2.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 21.01,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 16.31,  2.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 27.05,  5.  ,  0.  ,  1.  ,  6.  ],
       [ 1.  ,  0.  ,  0.  , 13.81,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.77,  2.23,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 12.43,  1.8 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 13.39,  2.61,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 10.33,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 35.26,  5.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 35.83,  4.67,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 12.69,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 14.07,  2.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 24.59,  3.61,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 14.26,  2.5 ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.06,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 34.3 ,  6.7 ,  0.  ,  1.  ,  6.  ],
       [ 0.  ,  1.  ,  0.  , 31.85,  3.18,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.02,  1.98,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  8.51,  1.25,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 11.38,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 12.16,  2.2 ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 40.55,  3.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 12.02,  1.97,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.47,  3.23,  1.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 17.59,  2.64,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 30.4 ,  5.6 ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 30.14,  3.09,  1.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 16.04,  2.24,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 15.95,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 39.42,  7.58,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 45.35,  3.5 ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  9.6 ,  4.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.66,  3.4 ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 31.27,  5.  ,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 20.53,  4.  ,  1.  ,  1.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 32.4 ,  6.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  , 22.75,  3.25,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 20.69,  5.  ,  0.  ,  0.  ,  5.  ],
       [ 0.  ,  1.  ,  0.  ,  9.68,  1.32,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  8.35,  1.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 15.69,  1.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 23.68,  3.31,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 15.36,  1.64,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  9.94,  1.56,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 12.26,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 13.42,  3.48,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 32.83,  1.17,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 10.09,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 18.04,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 13.81,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 19.44,  3.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.78,  3.27,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 12.74,  2.01,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 26.88,  3.12,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 15.81,  3.16,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 14.  ,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 22.49,  3.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 32.68,  5.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.59,  1.5 ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  8.58,  1.92,  1.  ,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  , 21.16,  3.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 15.04,  1.96,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 18.43,  3.  ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 48.27,  6.73,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 12.76,  2.23,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 20.27,  2.83,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 16.29,  3.71,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 20.76,  2.24,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 26.86,  3.14,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.61,  3.39,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.26,  3.25,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.51,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 13.42,  1.58,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 18.29,  3.76,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 25.56,  4.34,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 25.21,  4.29,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 12.54,  2.5 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 24.01,  2.  ,  1.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 16.82,  4.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 48.33,  9.  ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  , 23.1 ,  4.  ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 27.18,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 12.9 ,  1.1 ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 10.63,  2.  ,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 11.24,  1.76,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 28.55,  2.05,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 24.71,  5.85,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 20.29,  2.75,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 26.41,  1.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 16.4 ,  2.5 ,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 21.5 ,  3.5 ,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 12.6 ,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 30.46,  2.  ,  1.  ,  0.  ,  5.  ],
       [ 0.  ,  0.  ,  1.  , 19.81,  4.19,  1.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 22.82,  2.18,  0.  ,  1.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 16.93,  3.07,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 25.  ,  3.75,  0.  ,  0.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  , 22.12,  2.88,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 10.34,  1.66,  0.  ,  0.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  , 34.81,  5.2 ,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  7.51,  2.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 19.08,  1.5 ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 13.13,  2.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 22.42,  3.48,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  , 12.46,  1.5 ,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 29.93,  5.07,  0.  ,  0.  ,  4.  ],
       [ 0.  ,  0.  ,  1.  , 18.28,  4.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 13.  ,  2.  ,  1.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 14.73,  2.2 ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 28.17,  6.5 ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 30.06,  2.  ,  1.  ,  0.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  , 13.42,  1.68,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  , 18.78,  3.  ,  0.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 17.92,  4.08,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 18.15,  3.5 ,  1.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 17.07,  3.  ,  0.  ,  0.  ,  3.  ],
       [ 1.  ,  0.  ,  0.  , 20.49,  4.06,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 14.83,  3.02,  0.  ,  0.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  5.75,  1.  ,  1.  ,  0.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  , 34.63,  3.55,  1.  ,  0.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  , 44.3 ,  2.5 ,  1.  ,  0.  ,  3.  ]])